name: Deploy Workflow
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run Lint Script
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Run Test Script
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy
        run: npm run build
  finish:
    runs-on: ubuntu-latest
    needs: [setup, lint, test, deploy]
    steps:
      - name: Finish
        run: echo "Deployment finished!!!!"
